### ISSUE TITLE
[javascript] Warning: TypeError: navigationContainer.isReady is not a function (it is undefined)

### ISSUE THREAD

**Issue by kiet-ap** [bugsnag/bugsnag-js-performance#732]
### Steps to reproduce
1. Clone this repo: https://github.com/kiet-ap/BugsnagNavigationBug
2. Add your api key to index.js, android/app/src/main/AndroidManifest.xml, ios/BugsnagNavigationBug/Info.plist
3. Run app with: npm run start, npm run android

### Environment
* BugSnag Performance library version:     "@bugsnag/react-native-performance": "^3.1.0"
* BugSnag Error Monitoring library version (if any):     "@bugsnag/react-native": "^8.7.0"
* Browser framework version (if any):
    * Vue:
    * React:
    * Angular:
* Server framework version (if any):
    * Koa:
    * Express:
    * Restify:
* Browser version (e.g. chrome, safari):
* Device (e.g. iphonex): Android 15, Pixel 7a

### Example Repo 

- [x] Create a minimal repository that can reproduce the issue
- [x] Link to it here: https://github.com/kiet-ap/BugsnagNavigationBug

</details>

I can’t integrate both BugsnagPluginReactNavigationNativePerformance and BugsnagPluginReactNavigation at the same time, but each one works fine individually.
	•	Using only BugsnagPluginReactNavigationNativePerformance works. ✅
	•	Using only BugsnagPluginReactNavigation works. ✅
	•	However, integrating both as described in the documentation causes an error. ❌

Please let me know if you need any additional information.

**Comment by yousif-bugsnag** [comment]
Hi @kiet-ap, thanks for raising this, and thanks for your patience while we looked into this.

This is indeed a bug due to some subtle differences between the implementations of the two plugins. 

When the error notifier plugin is the outer wrapper, it passes a regular `React.useRef` through to the performance plugin, so the ref's `current` is `null` when the performance plugin tries to call `isReady`. 

We have a fix incoming to make sure that the navigation container is ready before initializing the performance plugin, but in the meantime you should be able to work around the issue simply by reversing the order of the plugins so that the performance plugin is the outer wrapper - i.e. wrap the 'real' `NavigationContainer` with the error notifier's plugin and then pass this to the performance plugin.
